server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: libro-books
              uri: lb://libro-service
              predicates:
                - Path=/api/v1/books,/api/v1/books/**
                - Method=GET
            - id: membresia-plans
              uri: lb://membresia-service
              predicates:
                - Path=/api/v1/memberships/plans,/api/v1/memberships/plans/*
                - Method=GET
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
