spring.application.name=SAIBM
server.port=8000

spring.datasource.url=${SAIBM_DB_URL}
spring.datasource.username=${SAIBM_DB_USER}
spring.datasource.password=${SAIBM_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.sql.init.mode=never

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.config.import=optional:file:env.properties

recaptcha.sitekey=${SAIBM_RECAPTCHA_SITE_KEY}
recaptcha.secret=${SAIBM_RECAPTCHA_SECRET}

api.name.author=saimb
