create table books (
    id integer generated by default as identity primary key,
    title varchar(255) not null,
    description text not null default '',
    author varchar(255) not null,
    image_url varchar(300) not null default '',
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index idx_books_active_title_id on books (active, title, id);
create index idx_books_active_author on books (active, author);

create table inventory (
    book_id integer primary key references books(id),
    total_stock integer not null check (total_stock >= 0),
    available_stock integer not null check (available_stock >= 0 and available_stock <= total_stock),
    updated_at timestamptz not null default now()
);

create table inventory_holds (
    id bigint generated by default as identity primary key,
    operation_key varchar(200) not null unique,
    book_id integer not null references books(id),
    quantity integer not null check (quantity > 0),
    expires_at timestamptz not null,
    request_hash varchar(64) not null,
    state varchar(16) not null check (state in ('HELD', 'COMMITTED', 'RELEASED', 'EXPIRED')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index idx_inventory_holds_book_state on inventory_holds (book_id, state);
